# Generated by Django 4.2.5 on 2023-10-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postagens.postagem'),
        ),
    ]
