# Generated by Django 4.2.5 on 2023-10-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0003_alter_comentario_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_coments', to='postagens.postagem'),
        ),
    ]
