# Generated by Django 4.2.5 on 2023-10-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0004_alter_comentario_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
