# Generated by Django 4.2.5 on 2023-10-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0006_alter_comentario_options_remove_comentario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
